
package mx.com.asteci.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProductWebService", targetNamespace = "http://ws.asteci.com.mx/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductWebService {


    /**
     * 
     * @param request
     * @return
     *     returns mx.com.asteci.ws.CreateProductResponseType
     * @throws ValidationException
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "createProduct", targetNamespace = "http://ws.asteci.com.mx/", className = "mx.com.asteci.ws.CreateProduct")
    @ResponseWrapper(localName = "createProductResponse", targetNamespace = "http://ws.asteci.com.mx/", className = "mx.com.asteci.ws.CreateProductResponse")
    public CreateProductResponseType createProduct(
        @WebParam(name = "request", targetNamespace = "")
        CreateProductRequestType request)
        throws ValidationException
    ;

    /**
     * 
     * @return
     *     returns mx.com.asteci.ws.ListProductsResponseType
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "listProducts", targetNamespace = "http://ws.asteci.com.mx/", className = "mx.com.asteci.ws.ListProducts")
    @ResponseWrapper(localName = "listProductsResponse", targetNamespace = "http://ws.asteci.com.mx/", className = "mx.com.asteci.ws.ListProductsResponse")
    public ListProductsResponseType listProducts();

}
