
package mx.com.asteci.ws;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ValidationFault", targetNamespace = "http://ws.asteci.com.mx/")
public class ValidationException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ValidationFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ValidationException(String message, ValidationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ValidationException(String message, ValidationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mx.com.asteci.ws.ValidationFault
     */
    public ValidationFault getFaultInfo() {
        return faultInfo;
    }

}
